[package]
name = "MFEKmath"
version = "0.1.0"
authors = ["Matthew Blanchard <matthewrblanchard@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
skia-safe = "0"
flo_curves = { git = "https://github.com/MFEK/flo_curves", branch = "master" }
glifparser = { git = "https://github.com/MFEK/glifparser.rlib" }
xmltree = "0.10.1"
xmlwriter = "0.1.0"
