[package]
name = "MFEKMath"
version = "0.1.0"
authors = ["Matthew Blanchard <matthewrblanchard@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
skia-safe = "0"
flo_curves = { path = "../flo_curves"}
glifparser = { path = "../glifparser" }
xmltree = "0.10.1"
xmlwriter = "0.1.0"
